version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - STUB_MODE=false
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AUTO_CLOSE_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.78
      - AGENT_SERVICE_URL=http://agent-worker:8000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
      - agent-worker

  agent-worker:
    build: ./agent-worker
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - STUB_MODE=false
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./agent-worker:/app
    depends_on:
      - redis

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=helpdesk

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
